version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - '5423:5432'
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      SIMPLE_COURSES_DATABASE_PASSWORD: password
      SIMPLE_COURSES_DATABASE_HOST: database
